
version: '3'
services:
  audiobook-organizer:
    image: audiobook-organizer
    build: .
    ports:
      - "5800:5800"
    volumes:
      - /path/to/audiobooks:/audiobooks
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
